[build-system]
requires = ["setuptools>=65", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tide-lite"
version = "0.1.0"
description = "Temporally-Indexed Dynamic Embeddings - Lightweight implementation"
readme = "README.md"
requires-python = ">=3.10"
license = {file = "LICENSE"}
authors = [
    {name = "Your Name", email = "your.email@example.com"}
]
dependencies = [
    "torch>=2.1.0",
    "transformers>=4.44.0",
    "datasets>=2.20.0",
    "sentence-transformers>=3.0.0",
    "faiss-cpu>=1.7.4",
    "scikit-learn>=1.4.0",
    "numpy>=1.26.0",
    "pandas>=2.0.0",
    "tqdm>=4.66.0",
    "matplotlib>=3.8.0",
    "peft>=0.12.0",
    "pydantic>=2.5.0",
    "pyyaml>=6.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.4.0",
    "pytest-cov>=4.1.0",
    "ruff>=0.1.0",
    "black>=23.0.0",
    "isort>=5.12.0",
    "mypy>=1.7.0",
    "ipykernel>=6.25.0",
]

[project.scripts]
tide-train = "tide_lite.cli.train:main"
tide-eval = "tide_lite.cli.evaluate:main"
tide-predict = "tide_lite.cli.predict:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
tide_lite = ["py.typed"]

[tool.ruff]
target-version = "py310"
line-length = 100
select = [
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings
    "F",    # pyflakes
    "I",    # isort
    "B",    # flake8-bugbear
    "C4",   # flake8-comprehensions
    "UP",   # pyupgrade
    "ARG",  # flake8-unused-arguments
    "SIM",  # flake8-simplify
]
ignore = [
    "E501",  # line too long (handled by black)
    "B008",  # do not perform function calls in argument defaults
    "C901",  # too complex
]
exclude = [
    ".git",
    "__pycache__",
    "build",
    "dist",
    ".venv",
    "venv",
]

[tool.ruff.isort]
known-first-party = ["tide_lite"]

[tool.black]
line-length = 100
target-version = ["py310"]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
line_length = 100
known_first_party = ["tide_lite"]
skip_gitignore = true

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_any_unimported = false
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
check_untyped_defs = true
strict_equality = true

[[tool.mypy.overrides]]
module = [
    "transformers.*",
    "datasets.*",
    "sentence_transformers.*",
    "faiss.*",
    "sklearn.*",
    "tqdm.*",
    "yaml.*",
]
ignore_missing_imports = true

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = [
    "-v",
    "--cov=tide_lite",
    "--cov-report=term-missing",
    "--cov-report=html",
]
