# Data configuration
dataset:
  name: "arxiv_cs_ml"  # HuggingFace dataset or CSV path
  text_field: "abstract"
  title_field: "title"
  id_field: "paper_id"
  year_field: "year"

buckets:
  # Time period definitions
  - name: "early"
    range: [null, 2018]  # ≤2018
  - name: "recent"
    range: [2019, 2024]  # 2019-2024

sampling:
  max_per_bucket: 6000  # Limit samples per bucket for fast training
  seed: 42
  stratify: true  # Balance across years within each bucket

preprocessing:
  min_abstract_length: 50  # Minimum abstract length (chars)
  max_abstract_length: 2000  # Maximum abstract length (chars)
  remove_duplicates: true
