# Evaluation configuration
retrieval:
  mode: "multi-index"  # Options: "time-select" or "multi-index"
  
  # Multi-index merge strategies
  merge_strategy: "softmax"  # Options: softmax, mean, max, rrf
  temperature: 2.0  # Temperature for softmax merge
  
  # Top-K for retrieval
  top_k: 100  # Retrieve top 100 for metrics

metrics:
  # Primary metrics
  compute:
    - "ndcg@10"
    - "recall@10"
    - "recall@100"
    - "mrr"
  
  # Statistical tests
  bootstrap:
    enabled: true
    n_samples: 1000
    confidence: 0.95
  
  permutation_test:
    enabled: true
    n_permutations: 1000
    baseline: "static"  # Compare LoRA vs static embeddings

scenarios:
  # Evaluation scenarios
  - name: "within"
    description: "Query and documents from same period"
  - name: "cross"
    description: "Query from one period, documents from another"
  - name: "all"
    description: "Query against all documents regardless of period"

test_split:
  size: 0.2  # Use 20% of data for testing
  seed: 42
  stratify: true  # Stratify by time bucket
