# Small benchmark configuration - for quick GPU runs
# ~15-30 minutes on GPU

# Model configuration
encoder_name: "sentence-transformers/all-MiniLM-L6-v2"
hidden_dim: 384
time_encoding_dim: 32
mlp_hidden_dim: 128
mlp_dropout: 0.1
freeze_encoder: true
pooling_strategy: "mean"
gate_activation: "sigmoid"

# Data configuration
batch_size: 64
eval_batch_size: 128
max_seq_length: 128
num_workers: 2

# Training configuration
num_epochs: 2
learning_rate: 5.0e-5
warmup_steps: 50
weight_decay: 0.01
gradient_clip: 1.0

# Loss weights
temporal_weight: 0.15
preservation_weight: 0.05
tau_seconds: 86400.0

# Mixed precision
use_amp: true  # Enable for GPU

# Checkpointing
save_every_n_steps: 200
eval_every_n_steps: 100

# Output paths
output_dir: "outputs/bench_small"
checkpoint_dir: "outputs/bench_small/checkpoints"

# Misc
seed: 42
log_level: "INFO"
dry_run: false
device: "auto"  # Will use GPU if available
temporal_enabled: true
