# TIDE-Lite Google Colab Configuration
# Minimal overrides for Colab environment - inherits all defaults

# Use GPU in Colab
device: "cuda"

# Colab-specific output directory
out_dir: "/content/drive/MyDrive/tide_results"

# Larger batch sizes for GPU
batch_size: 128
eval_batch_size: 256

# Colab has good CPU count
num_workers: 4

# More frequent evaluation in Colab for monitoring
eval_every: 50

# Cache in Colab's persistent storage if mounted
cache_dir: "/content/drive/MyDrive/tide_cache"

# TimeQA data in Drive if available
timeqa_data_dir: "/content/drive/MyDrive/datasets/timeqa"

# TempLAMA path for Colab
templama_path: "/content/drive/MyDrive/datasets/templama"

# Use mixed precision (Colab GPUs support it)
use_amp: true

# Higher logging for debugging in notebooks
log_level: "DEBUG"
