# Default configuration for TIDE-Lite training
# Override these values via command-line arguments or custom config files

# Model configuration
encoder_name: "sentence-transformers/all-MiniLM-L6-v2"
hidden_dim: 384
time_encoding_dim: 32
mlp_hidden_dim: 128
mlp_dropout: 0.1
freeze_encoder: true
pooling_strategy: "mean"

# Data configuration
batch_size: 32
eval_batch_size: 64
max_seq_length: 128
num_workers: 2

# Training configuration
num_epochs: 3
learning_rate: 5.0e-5
warmup_steps: 100
weight_decay: 0.01
gradient_clip: 1.0

# Loss weights
temporal_weight: 0.1
preservation_weight: 0.05
tau_seconds: 86400.0  # 1 day

# Mixed precision
use_amp: true

# Checkpointing
save_every_n_steps: 500
eval_every_n_steps: 500

# Misc
seed: 42
log_level: "INFO"
dry_run: false
