name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov black isort mypy flake8
    
    - name: Format check with black
      run: |
        black src/ tests/ --check --line-length 100
    
    - name: Import sort check with isort
      run: |
        isort src/ tests/ --check --profile black --line-length 100
    
    - name: Lint with flake8
      run: |
        flake8 src/ tests/ --max-line-length 100 --ignore E203,W503
    
    - name: Type check with mypy
      run: |
        mypy src/tide_lite --ignore-missing-imports
    
    - name: Run tests
      run: |
        pytest tests/ -v --tb=short --cov=tide_lite --cov-report=xml
    
    - name: Upload coverage to Codecov
      if: matrix.python-version == '3.9'
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
    
    - name: Test CLI dry-run
      run: |
        # Test that CLI commands work in dry-run mode
        python -m tide_lite.cli.tide --help
        python -m tide_lite.cli.tide train --help
        python -m tide_lite.cli.tide bench-all --model minilm --type baseline
        python -m tide_lite.cli.tide ablation --time-mlp-hidden 64,128

  integration:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install package
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install -r requirements.txt
    
    - name: Test import
      run: |
        python -c "import tide_lite; print('TIDE-Lite imported successfully')"
        python -c "from tide_lite.models.tide_lite import TIDELite; print('Model imported')"
    
    - name: Dry-run smoke test
      run: |
        # Quick smoke test with minimal config
        python -m tide_lite.cli.tide train --num-epochs 1 --batch-size 4
        python -m tide_lite.cli.tide eval-stsb --model minilm --type baseline
        python -m tide_lite.cli.tide eval-quora --model minilm --type baseline
        python -m tide_lite.cli.tide eval-temporal --model minilm --type baseline
